### ISSUE TITLE
NoClassDefFoundError: com/google/common/collect/Maps

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gdata-java-client#180]
```
What steps will reproduce the problem?
1. When Im trying to create this:

myService = new SpreadsheetService( "Teste" );

I got a error:

Error:
Exception in thread "main" java.lang.NoClassDefFoundError:
com/google/common/collect/Maps
        at
com.google.gdata.wireformats.AltRegistry.<init>(AltRegistry.java:118)
        at
com.google.gdata.wireformats.AltRegistry.<init>(AltRegistry.java:100)
        at com.google.gdata.client.Service.<clinit>(Service.java:532)
        at RotorTecnology.GoogleGenericDB.autentic(GoogleGenericDB.java:48)
        at RotorTecnology.GoogleGenericDB.main(GoogleGenericDB.java:315)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Maps
        at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
        ... 5 more
```

Original issue reported on code.google.com by `lcarle...@gmail.com` on 1 Sep 2009 at 1:59

**Comment by DocGreenRob** [comment]
is anyone reading these posts? I need assistance. Please respond to doc.green.rob@gmail.com subject "Email Audit Assistance".  I am willing to pay for assistance, just have a few questions to answer.

**Comment by montaro** [comment]
Thanks, adding latest Guava as dependency solved the problem.
