### ISSUE TITLE
Getting com.google.gdata.util.AuthenticationException

### ISSUE THREAD

**Issue by myluco** [google/gdata-java-client#451]
Since yesterday afternoon I am getting the AuthenticationException. Here is the error:

com.google.gdata.util.AuthenticationException: Error authenticating (check service name)
	at com.google.gdata.client.GoogleAuthTokenFactory.getAuthException(GoogleAuthTokenFactory.java:688)
	at com.google.gdata.client.GoogleAuthTokenFactory.getAuthToken(GoogleAuthTokenFactory.java:560)
	at com.google.gdata.client.GoogleAuthTokenFactory.setUserCredentials(GoogleAuthTokenFactory.java:397)
	at com.google.gdata.client.GoogleService.setUserCredentials(GoogleService.java:364)
	at com.google.gdata.client.GoogleService.setUserCredentials(GoogleService.java:319)
	at com.google.gdata.client.GoogleService.setUserCredentials(GoogleService.java:303)
	at freebies.coffinate.com.FreediesBatchFeedStandAlone.<init>(FreediesBatchFeedStandAlone.java:180)
	at freebies.coffinate.com.FreediesBatchFeedStandAlone.main(FreediesBatchFeedStandAlone.java:1177)

---> FreediesBatchFeedStandAlone.java:1177
FreediesBatchFeedStandAlone fr =   new FreediesBatchFeedStandAlone(new BloggerService("cbh-freebie-1"), userName,userPassword,"");

---> (FreediesBatchFeedStandAlone.java:180)
myService.setUserCredentials(un, password); 
(myService is the new BloggerService("cbh-freebie-1") )

I did not change the code. It works for several years, and yesterday afternoon (after my program ran successfully), I keep getting this error.
Any help is really appreciated, as I run my program everyday and post every day on my blog.
My blog is cbhscrapbookfreebiessearch.blogspot.com (but that should not be part of the problem imho)

**Comment by ejona86** [comment]
setUserCredentials() uses ClientLogin, which [has been deprecated since April 2012 and recently disabled](https://developers.google.com/identity/protocols/AuthForInstalledApps). You will need to use OAuth instead.
