### ISSUE TITLE
SpreadsheetService Authentication (Exception)

### ISSUE THREAD

**Issue by DevCubeHD** [google/gdata-java-client#464]
I know the method is deprecated but I never found a new method. The method setOAuth2Credentials() does not exist for me. Maybe the API is old?! Because it says version 1.0 here...
Thank you for your help

**Code:**
```
SpreadsheetService service = new SpreadsheetService("CloudSystem");
service.setUserCredentials(username, password);
```

**Error:**
```
Exception in thread "main" com.google.gdata.util.AuthenticationException: Error authenticating (check service name)
	at com.google.gdata.client.GoogleService.getAuthException(Unknown Source)
	at com.google.gdata.client.GoogleService.getAuthToken(Unknown Source)
	at com.google.gdata.client.GoogleService.setUserCredentials(Unknown Source)
	at com.google.gdata.client.GoogleService.setUserCredentials(Unknown Source)
	at de.devcubehd.spreadsheet.GoogleClient.<init>(GoogleClient.java:29)
	at de.devcubehd.spreadsheet.Main.main(Main.java:26)

```

**Comment by DevCubeHD** [comment]
Just the old sources...
